### ISSUE TITLE
With this buildpack, I got the error about rubygems version

### ISSUE THREAD

**Issue by hidehiro98** [bundler/heroku-buildpack-bundler2#4]
```
       bundler-2.0.0 requires rubygems version >= 3.0.0, which is incompatible with the
       current version, 2.7.6
```
I couldn't update the rubygems's version of the heroku stack.

**Comment by colby-swandale** [comment]
We have released Bundler 2.0.1 that allows versions of RubyGems 2.5.0 and up. It should work if you deploy your app again.
