### ISSUE TITLE
Releases fail with bundler version error

### ISSUE THREAD

**Issue by matthewrudy** [bundler/heroku-buildpack-bundler2#5]
So I can't work this one out.

Thinking maybe it's a heroku issue.

But here's the situation:

```
# Procfile
release: bundle exec rake db:migrate
web: bundle exec rails server -p $PORT -e $RAILS_ENV
```

the buildpack is set
```
$ heroku buildpacks --app redacted
=== redacted Buildpack URL
https://github.com/bundler/heroku-buildpack-bundler2.git
```

The build works fine:
```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.0
-----> Installing dependencies using bundler 2.0.1
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/.......
       Fetching rake 12.3.2
...
       
-----> Discovering process types
       Procfile declares types     -> release, web
       Default types for buildpack -> console, rake
-----> Compressing...
       Done: 50.5M
-----> Launching...
 !     Release command declared: this new release will not be available until the command succeeds.
       Released v7
       https://redacted.herokuapp.com/ deployed to Heroku
```

But then it goes on to run the release process

```
bundler: failed to load command: rake (/app/vendor/bundle/ruby/2.6.0/bin/rake)
Bundler::LockfileError: You must use Bundler 2 or greater with this lockfile.
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `new'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `initialize'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `new'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:34:in `build'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:135:in `definition'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:101:in `setup'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

As far as I'm aware, the `release` should just be running a command inside the container.

```
bundle exec rake db:migrate
```

So somehow the container's `bundle exec` isn't using 2.0.1.

I'll try and do some more debug,
but for now this is blocking me upgrading.

**Comment by matthewrudy** [comment]
I made a simple way to reproduce this

``` bash
git clone https://github.com/matthewrudy/bundler2-heroku-example.git
cd bundler2-heroku-example
heroku create
heroku buildpacks:set https://github.com/bundler/heroku-buildpack-bundler2.git
git push heroku master
```

Here's a gist running it on my machine.
https://gist.github.com/matthewrudy/c8ad3854e4b69098e5a95019478adc0d

**Comment by Evlos** [comment]
Same here.

**Comment by asa644** [comment]
Same here!

**Comment by pepicrft** [comment]
Same here. Even though it seems to be using Bundler 2.0.1 when building the app, when I run:

```bash
heroku run bundle version

$ Bundler version 1.17.2 (2018-12-19 commit 3fc4de72b)
```

My guess is that Bundler 2.0.1 is installed, but the environment points to the old version.

**Comment by matthewrudy** [comment]
@pepibumur yeah, there's some difference in the env for `heroku run` vs the buildpack.

I guess it's a heroku issue, rather than a buildpack one?

But can't be sure.

**Comment by MittchoBaroco** [comment]
Same here :(

**Comment by DrYurii** [comment]
Same error here. After trying multiple approaches, I had to downgrade bundler to 1.17.3 version, which seems to be the only way around it for now, see:

https://github.com/bundler/bundler/issues/6784#issuecomment-457297894

**Comment by matthewrudy** [comment]
Thought this might fix it:
https://github.com/heroku/heroku-buildpack-ruby/pull/850

But seems not

**Comment by travisp** [comment]
@matthewrudy It should fix it! But I believe that even though the heroku fix has been merged into master, heroku hasn't yet released the new official version. You can force heroku to use the master branch by specifying the full git url as the buildpack, but my personal preference is to just downgrade to bundler 1 until they release the new version (it looks like Heroku releases a new buildpack version once per month, so it should be soon).

**Comment by matthewrudy** [comment]
@travisp that is what I did, actually.

Added the git remote directly.

But got the same issue.

**Comment by matthewrudy** [comment]
(should have included my script output to show ... But the same error as before)

**Comment by matthewrudy** [comment]
So v199 of the official ruby buildpack is now out,
and it doesn't work
so I will add a bug on their github.

**Comment by matthewrudy** [comment]
This is now resolved
Just have to use 2.6.1 with the default ruby buildpack.

Thanks everyone.
